### ISSUE TITLE
Can you please delete my paper on arxiv?

### ISSUE THREAD

**Issue by clytze0216** [LeeKyungwook/get-arxiv-noti#417]
hi,LeeKyungwook
Can you please delete my paper **UnICLAM:Contrastive Representation Learning with Adversarial Masking for Unified and Interpretable Medical Vision Question Answering** on arxiv? I can find my thesis on your website in the duplicate software, which leads to a high repetition rate. Thanks for your help.

Best regards,
Chenlu

**Comment by LeeKyungwook** [comment]
okay, I delete your paper!
