### ISSUE TITLE
could you please delete the edited record in this issue

### ISSUE THREAD

**Issue by clytze0216** [LeeKyungwook/get-arxiv-noti#422]
Hi, LeeKyungwook,

Thank you for your deletion!!! But I'm sorry that when I re-checked my article on turnitin, the result of the re-check was still able to retrieve the content you edited, so the result of the re-check was very high (the result showed that the re-checked was my own article), so I'm really sorry, could you please delete the edited record in this issue? 
Thank you so much！！
![image](https://user-images.githubusercontent.com/73174462/211276190-5aef2828-6555-4d76-9709-c86eb8b28f97.png)

![微信截图_20230109172413](https://user-images.githubusercontent.com/73174462/211276166-0a763fd4-def8-46b3-bd62-b7d0f5f960e6.png)

Best wishes,
Chenlu

**Comment by LeeKyungwook** [comment]
Okay
But, i can't find which issue your article was on. can you give me a issue title?

**Comment by clytze0216** [comment]
> Okay But, i can't find which issue your article was on. can you give me a issue title?

of course. the issue title is: New submissions for Thu, 22 Dec 22 #409
Thanks again!

**Comment by LeeKyungwook** [comment]
i delete it!
